### PR TITLE
Better align to original algorithm

### LINKED ISSUE #4: Setting a <key,value> is in fact O(N) amortized runtime
[hashlru](https://github.com/dominictarr/hashlru#algorithm) claims that each operation's runtime is O(1) (amortized).
This assertion isn't held in this implementation: whenever a new <key,value> pair is inserted (and it does not exist in `this.cache`, in line 19 the comparison `this.cache.size >= this.maxSize` calls the getter `size`. This getter iterates over the cache in each call. Therefore, when inserting N new <key,value> pairs, the getter will create a total of 1+2+...+N=O(N^2) iterations. When amortized for N insertions, this is O(N) runtime (amortized) per single insert operation.

### PR DESCRIPTION
**Pull request by sindresorhus**
Fixes #4

### CODE REVIEW

**Comment by asafch** [comment]
@sindresorhus I think the getter `size` in line 95 (pre-PR line no.) should also be amended.

**Comment by sindresorhus** [comment]
@asafch Agreed, see https://github.com/sindresorhus/quick-lru/pull/5/commits/1544acb9c12697be49fa15cf4ef80b991e646ad3

**Comment by asafch** [comment]
@sindresorhus I don't think this solves the problem. In the worst case `oldCache` is full, so you still perform O(N) operations for a single call of `size` (only this time it's 'normal' runtime and not amortized).

**Comment by sindresorhus** [comment]
> I don't think this solves the problem. In the worst case oldCache is full, so you still perform O(N) operations for a single call of size (only this time it's 'normal' runtime and not amortized).

True, but I fixed the main issue which was with `.set()`. I don't think people would use `.size` as often anyway. `hashlru` doesn't even have a `.size` property. I just added it for convenience.

> is it possible do have a different method that account for duplicates between oldCache and cache?

I don't think that worth the complication, for the reason stated above.

**Comment by asafch** [comment]
@sindresorhus seems like a fair compromise.

**Comment by sindresorhus** [comment]
@asafch Cool. Thanks for reporting and reviewing :)

**Pull request merged**
