### PR TITLE
Fix cache size becoming double of the defined size

### LINKED ISSUE #10: Actual cache size can go to double the maxSize
[Issuehunt badges](https://issuehunt.io/r/sindresorhus/quick-lru/issues/10)

When the main cache is filled, items are moved to oldCache. Now, it starts getting items from oldCache and puts in cache when they are accessed. Here, the items still remain in oldCache so in some cases, the memory use will be double where oldCache is full and the new cache has maxSize - 1 items.

Can the cache be deleted from oldCache after it's moved to current cache?
https://github.com/sindresorhus/quick-lru/blob/master/index.js#L32

> There is a $60.00 open bounty on this issue. Add more on [Issuehunt](https://issuehunt.io/r/sindresorhus/quick-lru/issues/10).
> - Checkout the [Issuehunt explorer](https://issuehunt.io/r/sindresorhus/quick-lru/) to discover more funded issues.
> - Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on Issuehunt to raise funds.

### PR DESCRIPTION
**Pull request by adityapatadia**
this closes #10

### CODE REVIEW

**Comment by sindresorhus** [comment]
Can you add a test?

**Comment by sindresorhus** [comment]
The PR title could also be made clearer. It should describe what it fixes, not what was implemented.

**Comment by adityapatadia** [comment]
I have added tests.

**Comment by Hongarc** [comment]
> I have added tests.

This test can check your code

**Comment by adityapatadia** [comment]
@Hongarc it would be great if you can elaborate this.

**Comment by adityapatadia** [comment]
@Hongarc thanks a lot for PR.

**Comment by adityapatadia** [comment]
I think this can be merged now.

**Comment by Hongarc** [comment]
> I think this can be merged now.

Just wait, he has too many pull requests need to review.

**Comment by adityapatadia** [comment]
I can see it on his profile 😁

**Comment by sindresorhus** [comment]
Looks good. Thank you @adityapatadia :)

**Comment by sindresorhus** [comment]
@adityapatadia => https://github.com/sindresorhus/quick-lru/issues/17

**Pull request merged**
